fraternidade.btc/Controllers/BlogController.cs
using System.Web.Mvc;


namespace fraternidade.btc.Controllers
{
    
    
    public class BlogController : Controller
    {
        
        public ActionResult Home1()
        {
            return View();
        }
        
        public ActionResult Home2()
        {
            return View();
        }
        
        public ActionResult Post()
        {
            return View();
        }
    }
}

fraternidade.btc/Controllers/OtherController.cs
using System.Web.Mvc;


namespace fraternidade.btc.Controllers
{
    
    
    public class OtherController : Controller
    {
        
        public ActionResult FullWidth()
        {
            return View();
        }
        
        public ActionResult SideBar()
        {
            return View();
        }
        
        public ActionResult Faq()
        {
            return View();
        }
        
        public ActionResult FourOhFour()
        {
            return View();
        }
    }
}

fraternidade.btc/Controllers/PortfolioController.cs
using System.Web.Mvc;


namespace fraternidade.btc.Controllers
{
    
    
    public class PortfolioController : Controller
    {
        
        public ActionResult OneColumn()
        {
            return View();
        }
        
        public ActionResult TwoColumn()
        {
            return View();
        }
        
        public ActionResult ThreeColumn()
        {
            return View();
        }
        
        public ActionResult FourColumn()
        {
            return View();
        }
        
        public ActionResult SingleItem()
        {
            return View();
        }
    }
}

fraternidade.btc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Modern Business - @ViewBag.Title</title>

    <!-- Bootstrap -->
    <link href="@Url.Content("/css/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("/css/modern-business.css")" rel="stylesheet">

    <!-- Login Page -->
    <link href="@Url.Content("/css/login.css")" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it) -->
                @Html.ActionLink("Fraternidade BITCOIN", "Index", new { controller = "Home" }, new { @class = "navbar-brand" })
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li id="about">
                       @Html.ActionLink("About", "Index", "About")
                    </li>
                    <li id="services">
                        @Html.ActionLink("Services", "Index", "Services")
                    </li>
                    <li id="contact">
                        @Html.ActionLink("Contact", "Index", "Contact")
                    </li>
                    <li id="usuarios">
                        @Html.ActionLink("Usuarios", "Index", "Usuarios")
                    </li>
                    <li id="portfolio" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Portfolio <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li id="1columnportfolio">
                                @Html.ActionLink("1 Column Portfolio", "OneColumn", "Portfolio")
                            </li>
                            <li id="2columnportfolio">
                                @Html.ActionLink("2 Column Portfolio", "TwoColumn", "Portfolio")
                            </li>
                            <li id="3columnportfolio">
                                @Html.ActionLink("3 Column Portfolio", "ThreeColumn", "Portfolio")
                            </li>
                            <li id="4columnportfolio">
                                @Html.ActionLink("4 Column Portfolio", "FourColumn", "Portfolio")
                            </li>
                            <li id="singleportfolioitem">
                                @Html.ActionLink("Single Portfolio Item", "SingleItem", "Portfolio")
                            </li>
                        </ul>
                    </li>
                    <li id="blog" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li id="bloghome1">
                                @Html.ActionLink("Blog Home 1", "Home1", "Blog")
                            </li>
                            <li id="bloghome2">
                                @Html.ActionLink("Blog Home 2", "Home2", "Blog")
                            </li>
                            <li id="blogpost">
                                @Html.ActionLink("Blog Post", "Post", "Blog")
                            </li>
                        </ul>
                    </li>
                    <li id="other" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Other Pages <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li id="fullwidthpage">
                                @Html.ActionLink("Full Width Page", "FullWidth", "Other")
                            </li>
                            <li id="sidebarpage">
                                @Html.ActionLink("Sidebar Page", "Sidebar", "Other")
                            </li>
                            <li id="faq">
                                @Html.ActionLink("FAQ", "Faq", "Other")
                            </li>
                            <li id="404">
                                @Html.ActionLink("404", "FourOhFour", "Other")
                            </li>
                            
                        </ul>
                    </li>
                    @Html.Partial("_LoginPartial")
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    @RenderBody()

    <div class="container">

        <hr>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Company 2013</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

    <!--<script src="@Url.Content("/js/bootstrap.js")"></script>-->
   <!-- <script src="@Url.Content("/js/modern-business.js")"></script>-->
</body>
</html>